---
- name: This is the first play
  hosts: all
  tasks:

  - name: Installing IIS feature
    win_feature:
      name: Web-Server
      state: present

  - name: Starting IIS service
    win_service:
      name: W3Svc
      state: started

  - name: Creating website index.html
    win_copy:
      content: "Hello World!"
      dest: c:\Inetpub\wwwroot\index.html

- name: This is the second play
  hosts: all
  tasks:
    - name: Creating a directory
      win_file:
        path: c:\custom_share
        state: directory
    - name: Enabling the sharing
      win_share:
        name: windows_share
        description: This is a custom share
        path: c:\custom_share
        full: Administrator
        state: present
    - name: Copying some custom content
      win_copy:
        content: "This is a shared content"
        dest: c:\\custom_share\\shared.txt
...