---
- name: Testing complex condition with loop
  hosts: all
  vars:
    my_package:
    - jre8
    - javaruntime-preventasktoolbar
    - dropbox
  tasks:
    - name: Install packages
      win_chocolatey:
        name: "{{ item }}"
        state: present
        loop: "{{ my_package }}"
      when: ansible_facts['distribution'] == "Microsoft Windows Server 2016 Core" and ansible_facts['architecture'] == "64-bit" #Both conditions must be fulfilled.

      #You can also put something like
      when: 
        - ansible_facts['distribution'] == "Microsoft Windows Server 2016 Core"
        - ansible_facts['architecture'] == "64-bit"