---
- name: Take ownership and applying permissions
  hosts: all
  tasks:
    - name: Taking ownership of c:\temp\folder\test.conf
      win_owner:
        path: C:\temp\folder\test.conf
        user: xaAnsibleTest

    - name: Grant xaAnsibleTest Full permissions to c:\temp\folder\test.conf
      hosts: all
      tasks:
        win_acl:
          path: C:\temp\folder\test.conf
          user: user_global
          rights: FullControl
          type: allow
          state: present
