---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: First task - Install .NET 4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present
    notify:
    - reboot server
    
  - name: Purposely failing the second task
    debug:
      msg: failing the task to simulate test
    failed_when: true

  - name: This is the second task
    debug:
      msg: final task

  handlers:
    - name: reboot server
      win_reboot: