---
- name: Create a simple playbook
  hosts: all
  tasks:
  - name: Install IIS feature
    win_feature:
      name: Web-Server
      state: present
  - name: Start IIS service
    win_service:
      name: W3Svc
      state: started
  - name: Create website index.html
    win_copy:
      content: "Hello World!"
      dest: c:\Intepub\wwwroot\index.html
  - name: Reboot if installing Web-Server feature requires it
    win_reboot:
    when: win_feature.reboot_required
...