---
- name: Creating users
  hosts: all
  vars_files:
    - ./vars/users.yml
  tasks:
  - name: Creating user {usr}
    win_user:
      name: user_{{usr}}
      state: present
  - name: Creating xa[nodename]
    win_user:
      name: {{xaservername}}
      state: present
      groups: 
        - Administrators
      groups_action: add
...