---
- name: Creating users
  hosts: all
  vars:
    - usr: testuser
  tasks:
  - name: Creating user {usr}
    win_user:
      name: user_{usr}
      state: present
  - name: Creating xa{nodename}
    win_user:
      name: xa{nodename}
      state: present
      groups: 
        - Administrators
      groups_action: add
...