---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - name: First task - Install Flash Player
    win_chocolatey:
      name: flashplayerppapi
      state: present
    notify:
    - reboot server
    
  - name: Purposely failing the second task
    debug:
      msg: failing the task to simulate test
    failed_when: true

  - name: This is the third task
    debug:
      msg: final task

  handlers:
    - name: reboot server
      win_reboot: