---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install .NET 4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present
    notify:
    - reboot server
    
  - name: Purposely failing the task
    fail:

  handlers:
    - name: reboot server
      win_reboot: